### ISSUE TITLE
Uncaught TypeError: Cannot read property 'closeTab' of undefined

### ISSUE THREAD

**Issue by Poeschl** [olmokramer/atom-pane-split-moves-tab#2]
Right click on tab and select Split Tab to right causes this error.

**Atom Version**: 1.2.0
**System**: Linux Mint
**Thrown From**: [pane-split-moves-tab](https://github.com/olmokramer/atom-pane-split-moves-tab) package, v0.0.3
### Stack Trace

Uncaught TypeError: Cannot read property 'closeTab' of undefined

```
At /home/markus/.atom/packages/pane-split-moves-tab/lib/pane-split-moves-tab.js:38

TypeError: Cannot read property 'closeTab' of undefined
    at destroyTab (/home/markus/.atom/packages/pane-split-moves-tab/lib/pane-split-moves-tab.js:38:15)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at EventEmitter.ipc.sendSync (/opt/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/opt/atom/resources/atom.asar/renderer/api/lib/remote.js:138:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/atom/resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/opt/atom/resources/app.asar/src/window-event-handler.js:252:47)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -2:48.5.0 latex:build (atom-text-editor.editor.is-focused)
     -0:01.5.0 tabs:split-right (li.tab.sortable.modified.active.right-clicked)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-css",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-css",
      "language-go",
      "language-hyperlink",
      "language-java",
      "language-json",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-property-list",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-source",
      "language-sql",
      "language-toml",
      "language-xml",
      "language-yaml",
      "open-on-github",
      "welcome",
      "package-generator",
      "whitespace",
      "git-diff",
      "markdown-preview",
      "autocomplete-snippets",
      "snippets",
      "styleguide"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "linter-chktex"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-bibtex, v0.6.1
keyboard-localization, v1.4.10
language-latex, v0.6.1
latex, v0.28.2
latexer, v0.2.7
linter, v1.10.0
linter-chktex, v1.2.3
pane-split-moves-tab, v0.0.3
pdf-view, v0.34.0

# Dev
No dev packages
```

**Comment by bryanbraun** [comment]
I'm seeing the same thing on mine now... here's some information about my environment:

**Atom Version**: 1.3.2
**System**: OS X El Capitan
**Thrown From**: pane-split-moves-tab package, v0.0.3

My stack trace is the same.

**Comment by pedro93** [comment]
Seeing the same thing aswell on mine, my environment information

Atom Version: 1.5.4
System: OS X Yosemite 10.10.5
Thrown From: pane-split-moves-tab package, v0.0.3

My stack trace is the same.

**Comment by olmokramer** [comment]
I'm sorry for the late reply, I've been terribly busy over the last few months. Seems the `tabs` package stopped using space-pen to render the view... v0.1.0 of this package should fix this issue.

**Comment by Poeschl** [comment]
A little late for me to reply. But its fixed
