### ISSUE TITLE
Uncaught TypeError: tabBarView.closeTab is not a function

### ISSUE THREAD

**Issue by 8BitSaint** [olmokramer/atom-pane-split-moves-tab#4]
[Enter steps to reproduce:]

1. Right click tab
2. Choose any of the Split" options

**Atom**: 1.14.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [pane-split-moves-tab](https://github.com/olmokramer/atom-pane-split-moves-tab) package 0.1.0

### Stack Trace

Uncaught TypeError: tabBarView.closeTab is not a function

```
At /home/seanevans/.atom/packages/pane-split-moves-tab/lib/pane-split-moves-tab.js:10

TypeError: tabBarView.closeTab is not a function
    at destroyTab (/packages/pane-split-moves-tab/lib/pane-split-moves-tab.js:10:16)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:27.2.0 settings-view:uninstall-packages (input.hidden-input)
     -0:57.3.0 core:backspace (input.hidden-input)
  2x -0:53.6.0 core:confirm (input.hidden-input)
     -0:08.0 tabs:split-down (li.texteditor.tab.sortable.active.right-clicked)
```

### Non-Core Packages

```
pane-split-moves-tab 0.1.0 
print-atom 0.1.1 
```

**Comment by derwaldgeist** [comment]
+1

**Comment by derwaldgeist** [comment]
This is really getting on my nerves as it pops up every time I try to "split right". Could this be fixed pls? Thanks a lot! :-)

**Comment by Nickman87** [comment]
Yes please :)

**Comment by Stanzilla** [comment]
+1

**Comment by saikojosh** [comment]
+1

**Comment by dlewand691** [comment]
+1 please!

**Comment by thetwopct** [comment]
+1 please please

**Comment by derwaldgeist** [comment]
This was the reason why I disabled this package long ago.
Would love to see this fixed, though, since I am missing it.

**Comment by olmokramer** [comment]
Hi everyone, I'm sorry for the extremely late reply. As you have probably noticed I've stopped maintaining my Atom plugins a few years ago. I got very frustrated with how Atom was maintained and started ignoring all of my plugins. I'm sorry for that. I won't install Atom to test and merge PRs, but I'd be happy to transfer my repositories to anyone that wants to maintain any of my plugins. Again, I'm sorry.

**Comment by saikojosh** [comment]
No need to apologise. I’ve since moved to VS Code and I’m loving it!


Regards,
-Josh Cole.

**Comment by maneashmhzn** [comment]
..
